use kapacitor alert details as opsgenie description text
influxdata/kapacitor pull request #2409
Opened 2020-10-01 09:23 UTC by JamesClonk

This is a _breaking_ change in the OpsGenie plugin behaviour of Kapacitor. The modification will use alert/event state details as description when opening OpsGenie alerts instead. This allows much more descriptive alerts in OpsGenie. Alert details in OpsGenie are still filled with the same key/values as before.

The current behaviour of simply encoding the event details as description is imho not very useful as a value for an OpsGenie alert description, Kapacitor alert details can provide much more information and are more in line with OpsGenie alert descriptions.

Would such a change make sense, or is it too breaking in current behaviour?

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2020-10-01 15:05 UTC, docmerlin commented
@JamesClonk With this kind of breaking change, it would be a good idea to add a method to the node that tells it to do this behavior, so the new behavior is optional.

2020-10-03 08:36 UTC, JamesClonk commented
@docmerlin Makes sense, I'll have a look at it.

2020-10-09 19:11 UTC, docmerlin requested changes
We need a method on the node so you can select the breaking behavior while defaulting to current behavior.

2020-10-10 09:28 UTC, JamesClonk commented
@docmerlin I'm trying to figure out how to do that exactly. Is it enough to just add a field to the Config struct, does that automatically also add a method on the OpsGenie event handler node (It seems that way but I'm not 100% sure)?

2020-12-01 15:25 UTC, merged