chore(build): upgrade Go to 1.21.10, use custom builder instead of `cross-builder`
influxdata/kapacitor pull request #2819
Opened 2024-05-28 09:27 UTC by bednar

This PR introduces several changes:

1. Upgrades GoLang to `1.21.10`.
2. Upgrades the `protobuf` library to `3.18.3` and standardizes its use across the source base, including in `Dockerfile_build`, `build.sh`, and `test.sh`.
3. Utilizes a custom builder for Kapacitor instead of `cross-builder`.

2024-05-28 17:42 UTC, davidby-influx reviewed
I'm going to defer to @bnpfeife 's review of this...

2024-05-28 19:02 UTC, bnpfeife approved these changes
This looks good to me! It looks like there's no automation around building+pushing the custom builder docker image; however, since it's fairly straightforward to do the build+push from a developer machine, I'm not going to block on that.

Thank you for implementing this! My apologies for being absent from this effort, I've been swamped with several other projects.

2024-05-31 13:00 UTC, bednar commented on Dockerfile_build
> +ENV RUST_LATEST_VERSION=1.63.0
`Rust` has been updated to the latest version. I will prepare a `builder/README.md` file with documentation on how Kapacitor is built, including how to update builder components - Go, Rust, ...

2024-06-03 10:37 UTC, bednar commented on Dockerfile_build
> +ENV RUST_LATEST_VERSION=1.63.0
The `builder/README.md` is ready to review.

2024-06-03 12:49 UTC, jdstrand requested changes

2024-06-03 12:49 UTC, jdstrand commented on builder/Dockerfile_build_push.sh
> +#docker push quay.io/influxdb/builder:"$DOCKER_TAG"
This should be uncommented, no?

2024-06-03 14:34 UTC, jdstrand approved these changes
LGTM, thanks!

2024-06-04 03:46 UTC, merged